### ISSUE TITLE
All the SVGs are just planes

### ISSUE THREAD

**Issue by nano38** [MrJoy/UnitySVG#10]
I'm using unity 2019.1.0f2. The SVG files are just 2d boxes. Even in the example scenes they're just that.

**Comment by mattrdowney** [comment]
By now, it's better to use Unity's "Vector Graphics" preview package ( https://m.youtube.com/watch?v=BAyd5wSPQrM ).

UnitySVG was useful to me before Unity provided any support (thanks @MrJoy), but there have been a lot of developers working on .svg support in Unity so development stalled at some point.

**Comment by MrJoy** [comment]
@nano38 Strictly speaking, the SVG files are transformed into _textures_ and I'm using planes to render those textures.  That's not a bug, as such -- it's a deliberate design choice.  I can understand why you'd want a reified mesh that represents the geometry of the SVG, but that didn't fit with the problem I was trying to solve.  Had I done things that way, it would have been counter to my goals at the time:  Minimize download size for trial-to-pay games, without impacting runtime -- while still targeting Intel GMA 950 as my minspec GPU.  The hardware landscape is _really_ different now than it was when UnitySVG was developed, so the bake-to-texture approach is totally worth reconsidering -- but that would require a ground-up re-think of UnitySVG.

@mattrdowney Yeah, development was somewhat tripped up by the whole my-game-studio-ran-out-of-money-and-shut-down situation.  I'm glad it provided some value, but you're absolutely right that it's better to use something else at this point.  I'm not sure I'd be confident in any sort of "preview" package from Unity Technologies -- given their track record of half-baked ideas and abandoned features -- but the reality is that it's still a better bet than UnitySVG, even if it winds up abandoned if only because it'll get more attention and thus have more third-parties contributing to it.
